version: "3.7"
services:
  web:
    build: ./
    command: gunicorn --bind 0.0.0.0:$PORT manage:app
    volumes:
      - ./app/:/opt/app/
    ports:
      - $PORT:$PORT
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
volumes:
  postgres_data:
